[ADD] 상품 정보 UPDATE
wecode-bootcamp-korea/39-2nd-VVolt-Market-backend pull request #4
Opened 2022-12-02 12:15 UTC by Gyelanjjim

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 상품 정보 업데이트

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사
- 글로벌 에러핸들링 적용
- 본래 accessToken을 받으면 토큰 검증 미들웨어로 로그인한 사용자의 userId를 불러오는 과정이 필요하지만, 
  해당 부분을 주석처리하고 임의의 userId = 1로 테스트를 진행.
- (AWS S3 및 유닛테스트는 미적용)
<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="316" alt="스크린샷 2022-12-02 오후 7 24 44" src="https://user-images.githubusercontent.com/108852943/205287442-15444824-0521-4c60-b170-3b7ad6572b03.png">

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="1014" alt="스크린샷 2022-12-02 오후 6 45 56" src="https://user-images.githubusercontent.com/108852943/205287673-4bd0fea7-5df8-4510-b1d2-0a984002bc41.png">
<img width="1285" alt="스크린샷 2022-12-02 오후 6 46 24" src="https://user-images.githubusercontent.com/108852943/205287829-faa96ff9-98b2-48ee-8852-cf3a326b45ec.png">

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지 
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항

2022-12-06 07:47 UTC, bigfanoftim requested changes
테스트 코드에 대한 작업은 어떻게 진행할지 의견을 공유해주세요!

2022-12-06 07:47 UTC, bigfanoftim commented on src/controllers/product.controller.js
> +    const userId = 1; //req.user.id;
토큰을 처리할 수 있는 코드를 만드셔서 이 부분은 하드 코딩되어 있을 필요가 없어보입니다.

2022-12-06 07:47 UTC, bigfanoftim commented on src/controllers/product.controller.js
> +    return res.status(201).json({
201은 update를 의미하는 상태 코드가 아니니 수정해주세요.

2022-12-06 07:47 UTC, bigfanoftim commented on src/routes/product.router.js
> +//const { verifyToken } = require("../utils/verifyToken")
👀

2022-12-06 23:12 UTC, Gyelanjjim commented on src/controllers/product.controller.js
> +    const userId = 1; //req.user.id;
리뷰 반영했습니다

2022-12-07 02:05 UTC, bigfanoftim requested changes
이외에는 주석이 너무 많아 말씀드리기가 곤란합니다. 불필요한 주석은 최대한 지우시고 올려주시고 주석을 하신 타당한 이유가 있다면 그것에 대한 커멘트도 남겨주세요. PR로 소통하는 것은 개발자가 일을 할 때 갖춰야 할 가장 중요한 기술입니다.

2022-12-07 02:05 UTC, bigfanoftim commented on src/utils/imageUploader.js
> +      const uploadDirectory = req.query.directory ?? ''
`req.query.directory`를 보니 어디다 저장할지 클라이언트로 부터 받으려고 하시는게 맞을까요?
굳이 그럴 필요가 없어보입니다. 버킷 내 어느 디렉토리에 저장할지는 각 서비스의 서버에서 관리하는 것이 더 좋아보입니다.

2022-12-07 03:58 UTC, Gyelanjjim commented
직접 작성한 코드가 아니라 긁어온 자료라서 뭘 어떻게 물어봐야할지 모르겠습니다

AWS S3 생성, 
ACL 설정
region, access key, scret access key, bucket name을
.env 파일과 imageUploader.js 파일에 설정

routes:
const upload = require('../utils/imageUplaoder')
upload.single('string')  //이미지 1개
upload.array('string', 최대개수) //이미지 n개

...라는 미들웨어를 사용한다는 것까지 이해했습니다

2022-12-08 14:14 UTC, closed without merging