[ADD] 회원가입 및 로그인 API
wecode-bootcamp-korea/39-2nd-VVolt-Market-backend pull request #8
Opened 2022-12-04 10:18 UTC by lukas0306

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
카카오 소셜 로그인 및 테스트 코드 테스트

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
클라이언트로부터 카카오 code를 받아 카카오 서버에 token과 user정보 요청
받아온 user정보로 token생성 및 클라이언트에 응답.

<br />

## :: 테스트 결과 이미지
![스크린샷 2022-12-04 오후 7 12 57](https://user-images.githubusercontent.com/114485669/205485199-19bc9be8-df3e-4b11-b484-f310f87ffa9f.jpg)
![스크린샷 2022-12-04 오후 7 07 14](https://user-images.githubusercontent.com/114485669/205485201-1e2979c9-296e-4e36-9130-8ade89a6cf6c.jpg)

<br />

## :: 기타 질문 및 특이 사항
토큰 값이 계속 바뀌어서 토큰값으로는 테스트 fail밖에 안나오는 것 같은데 statuscode 200까지만 확인을 하는 게 맞는지
토큰을 decoding해서 id값으로 테스트를 해야되는지 아니면 아예 다른 방법으로 확인을 해야할지 모르겠습니다.

2022-12-05 02:02 UTC, bigfanoftim commented
토큰 값까지 테스트하고 싶으시다면 그자리에서 변하지 않는 string으로 넣는게 아니라 새로 토큰을 만드는 코드를 작성하는건 어떨까요? 어차피 userId가 몇이될지는 알 수 있으니까요.

2022-12-06 07:35 UTC, lukas0306 commented
로그인 시 회원가입 바로 되도록 로직 변경하였습니다.

2022-12-06 07:44 UTC, bigfanoftim requested changes

2022-12-06 07:44 UTC, bigfanoftim commented on db/migrations/20221129090702_users.sql
>      social_id varchar(50) NOT NULL,
기존에 작성된 migration 파일을 수정 및 적용하려면 DB를 Drop해야 합니다. 실제 서비스라면 그것이 불가능하기 때문에 수정이 필요하다면 새로운 migration 파일을 만들고 코드를 작성 후 dbmate up을 진행해야 합니다.

2022-12-06 07:44 UTC, bigfanoftim commented
테스트는 아직 해결이 안된걸까요?

2022-12-06 08:09 UTC, lukas0306 commented on db/migrations/20221129090702_users.sql
>      social_id varchar(50) NOT NULL,
넵

2022-12-06 08:10 UTC, lukas0306 commented
>

2022-12-08 04:49 UTC, bigfanoftim commented
수정이 안된것 같습니다. 확인한번 해보시겟어요?

2022-12-09 07:20 UTC, closed without merging