[MODIFY]
wecode-bootcamp-korea/39-2nd-VVolt-Market-backend pull request #9
Opened 2022-12-05 09:27 UTC by lukas0306

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
user정보 필수값 제거 입니다.

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
로그인 시 카카오에서 받아올 수 없는 정보가 있어서 회원가입할 때 빠져야할 필수값이 있어서 테이블 변경이 필요합니다.

<br />

## :: 테스트 결과 이미지
.

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-07 04:21 UTC, bigfanoftim requested changes

2022-12-07 04:21 UTC, bigfanoftim commented on .env.test
> +TYPEORM_DATABASE = vvoltMarketTest
👀
.env.test 또한 민감한 db 정보가 올라오니 .gitignore에 추가해주세요.

2022-12-07 18:55 UTC, lukas0306 commented on .env.test
> +TYPEORM_DATABASE = vvoltMarketTest
수정완료했습니다!

2022-12-08 04:49 UTC, bigfanoftim approved these changes
LGTM 👍

2022-12-08 04:49 UTC, merged